---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.6
  - name: ubuntu-12.04

suites:
    run_list:
      - recipe[ganeti::_test]
      - recipe[ganeti-instance-image]
      - recipe[test-instance-image]
    attributes:
      ganeti-instance-image:
        variants_list:
          - default
          - centos-6
      ganeti:
        master-node: true
        cluster:
          disk-templates:
            - "diskless"
          master-netdev: "lo"
          enabled-hypervisors:
            - "fake"
          nic:
            mode: "routed"
            link: "100"
          name: "ganeti.local"
