---
driver_config:
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD'] %>
  openstack_auth_url: <%= "#{ENV['OS_AUTH_URL']}/tokens" %>
  key_name: <%= ENV['OS_SSH_KEYPAIR'] %>
  private_key_path: <%= ENV['OS_PRIVATE_SSH_KEY'] %>
  public_key_path: <%= ENV['OS_PUBLIC_SSH_KEY'] %>
  openstack_tenant: <%= ENV['OS_TENANT_NAME'] %>
  floating_ip: <%= ENV['OS_FLOATING_IP'] %>
  floating_ip_pool: <%= ENV['OS_FLOATING_IP_POOL'] %>
  flavor_ref: <%= ENV['OS_FLAVOR_REF'] %>

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.6
    driver_plugin: openstack
    driver_config:
      username: centos
      image_ref: "CentOS 6.6"

suites:
  - name: default
    run_list:
      - recipe[ganeti::_test]
      - recipe[ganeti-instance-image]
      - recipe[test-instance-image]
    attributes:
      ganeti-instance-image:
        variants_list:
          - default
          - centos-6
      ganeti:
        master-node: true
        cluster:
          disk-templates:
            - "diskless"
          master-netdev: "lo"
          enabled-hypervisors:
            - "fake"
          nic:
            mode: "routed"
            link: "100"
          name: "ganeti.local"
