name             'ganeti-instance-image'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache 2.0'
description      'Installs/Configures ganeti-instance-image'
long_description 'Installs/Configures ganeti-instance-image'
supports         'centos', '~> 6.0'
supports         'ubuntu', '~> 12.04'

version          '0.1.0'
depends          'apt'
depends          'ganeti'
depends          'yum'
