name             'test-instance-image'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache 2.0'
description      'Installs/Configures test-instance-image'
long_description ''
version          '0.1.0'
depends          'ganeti-instance-image'
